version = 0.1
[default.deploy.parameters]
stack_name = "poc-parquet-publisher"
resolve_s3 = true
s3_prefix = "poc-parquet-publisher"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[local.deploy.parameters]
stack_name = "poc-parquet-publisher"
resolve_s3 = true
s3_prefix = "poc-parquet-publisher"
region = "us-east-1"
profile = "localstack"
capabilities = "CAPABILITY_IAM"
image_repositories = []
