AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for poc-parquet-publisher.

Resources:
  ParquetDataQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: parquet-data-queue
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ParquetDataDeadLetterQueue.Arn
        maxReceiveCount: 5
  ParquetDataDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: parquet-data-deadletter

  ParquetRecordPublisherFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: parquet-record-publisher
      Handler: bootstrap
      Runtime: provided.al2023
      CodeUri: cmd/record-publisher
      Environment:
        Variables:
          QUEUE_URL: !Ref ParquetDataQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt ParquetDataQueue.QueueName

  ParquetRecordConsumerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: parquet-record-consumer
      Handler: bootstrap
      Runtime: provided.al2023
      CodeUri: cmd/record-consumer
    Policies:
      - SQSPollerPolicy:
          QueueName: !GetAtt ParquetDataQueue.QueueName
    Events:
      ParquetDataQueue:
        Type: SQS
        Properties:
          Queue: !GetAtt ParquetDataQueue.Arn
