AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for poc-parquet-publisher.

Resources:
  ParquetDataQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "parquet-data-queue-${AWS::StackName}"
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ParquetDataDeadLetterQueue.Arn
        maxReceiveCount: 5
  ParquetDataDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "parquet-data-deadletter-${AWS::StackName}"

  DuckDBRecordProcessorFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: !Sub "duckdb-record-processor-${AWS::StackName}"
      Handler: bootstrap
      Runtime: provided.al2023
      CodeUri: .
      Architectures:
        - arm64
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Sub "arn:aws:s3:::${ParquetDataBucket}/*"

  SQSRecordConsumerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: !Sub "sqs-record-consumer-${AWS::StackName}"
      Handler: bootstrap
      Runtime: provided.al2023
      CodeUri: .
      Architectures:
        - arm64
    Policies:
      - SQSPollerPolicy:
          QueueName: !GetAtt ParquetDataQueue.QueueName
    Events:
      ParquetDataQueue:
        Type: SQS
        Properties:
          Queue: !GetAtt ParquetDataQueue.Arn

  ParquetDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "parquet-data-bucket-${AWS::StackName}"
